<?php
/**
 * Created by PhpStorm.
 * User: js
 * Date: 2019-03-07
 * Time: 14:31
 */

define('__WZ_BLOCK__', drupal_get_path('module', 'wz_block'));

/**
 * Implements hook_block_info().
 */
function wz_block_block_info()
{
    $blocks = array(
        'wz_main_slide' =>  array('info' => t('메인 슬라이드')),
        'wz_main_features' => array('info' => t('메인 주요 기사')),
        'wz_main_articles' => array('info' => t('메인 기타 기사')),
        'wz_main_newsletter' => array('info' => t('메인 뉴스레터')),
        'wz_footer' => array('info' => t('웹진 푸터'))
    );

    return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function wz_block_block_configure($delta = '')
{
    $form = array();

    switch ($delta) {
        case 'wz_main_newsletter':
            $form['newsletter_text'] = array(
                '#type' => 'textarea',
                '#title' => '안내문',
                '#default_value' => variable_get('newsletter_text', '')
            );
            $form['newsletter_action'] = array(
                '#type' => 'textfield',
                '#title' => 'Form action URL',
                '#default_value' => variable_get('newsletter_action', '')
            );
            break;
        case 'wz_footer':
            $form['wz_footer'] = array(
                '#type' => 'text_format',
                '#title' => '문구',
                '#default_value' => variable_get('wz_footer', '')
            );
            break;
    }

    return $form;
}

/**
 * Implements hook_block_save().
 */
function wz_block_block_save($delta = '', $edit = array())
{
    switch ($delta) {
        case 'wz_main_newsletter':
            variable_set('newsletter_text', $edit['newsletter_text']);
            variable_set('newsletter_action', $edit['newsletter_action']);
            break;
        case 'wz_footer':
            variable_set('wz_footer', $edit['wz_footer']['value']);
            break;
    }
}

/**
 * Implements hook_block_view().
 */
function wz_block_block_view($delta = '')
{
    $block = array();

    switch ($delta) {
        case 'wz_main_slide':
            $block['content'] = wz_main_slide_block_view();
            break;
        case 'wz_main_features':
            $block['content'] = wz_main_features_block_view();
            break;
        case 'wz_main_articles':
            $block['content'] = wz_main_articles_block_view();
            break;
        case 'wz_main_newsletter':
            $block['content'] = wz_main_newsletter_block_view();
            break;
        case 'wz_footer':
            $block['content'] = array(
              '#type' => 'markup',
              '#markup' => variable_get('wz_footer', '')
            );
            break;
    }

    return $block;
}

function wz_main_slide_block_view() {
    global $language;
    $lang = $language->language ?? 'und';
    $main = new Main();                 //메인페이지
    $slide = $main->slide();            //슬라이드
    $vol = $main->vol();
    $vol = sprintf('%02d', $vol);  //호수 노출
    $html = '<ul class="slide">';
    foreach($slide as $item) {
        if (!empty($item['fid'])) {
            $file = file_load($item['fid']);
            if(!empty($file)) {
                $img = image_style_url('main_slide', $file->uri);
                $target = ($item['blank']) ? ' target="_blank"' : '';
                $html .= '<li class="type01">
                    <a class="relative" href="'.$item['link'].'"'.$target.'>
                        <img class="max-w-none" src="'.$img.'" alt="'. htmlspecialchars(strip_tags($item['title'])) .'"/>
                        <dl>
                            <dt>' . $item['title'] . '</dt>
                            <dd>' .
                            str_replace('</br>', '', nl2br($item['body']));
                if ($lang == 'ko') {
                    $html .= '<p class="mt-3">-<br>글 ' . $item['authors'] . '</p>
                    <p>게시일 ' . $item['created'] . '</p>';
                }
                $html .='    </dd>
                        </dl>
                    </a>
                </li>';
            }
        }
    }
    $html .='</ul>';

    $block = array(
        'slide' => array(
            '#type' => 'markup',
            '#markup' => $html
        )
    );

    return $block;
}

function wz_main_features_block_view()
{
    $main = new Main();
    $features = $main->features();
    $html = '<div class="inner">';
    foreach ($features as $i => $rows) {
        $url = drupal_get_path_alias('taxonomy/term/' . $main->category[$i], 'ko');
        $class = ($i === 0) ? 'leftA' : 'rightA';
        $category_name = str_replace("category/", '', $url);
        $html .= '<div class="'.$class.'">
            <dl class="th01">
                <dt><h3>'.$main->featureLabel[$i].'</h3></dt>
                <dd><a href="/'.$url.'" class="btn_icon02" title="' . $category_name . ' 더보기"><i class="xi-plus"></i></a></dd>
            </dl>';
        foreach ($rows as $item) {
            $html .= '<div class="tc01 my-3 p-1">
                <a href="/node/'.$item['nid'].'" class="thumb"><img src="'.$item['img'].'" alt="'.htmlspecialchars($item['title']).'"/></a>
                <dl class="conA">
                    <dt><a href="/node/'.$item['nid'].'">'.$item['title'].'</a></dt>
                    <dd>'.$item['writer'].'</dd>
                </dl>
            </div>';
        }
        $html .= '</div>';
    }
    $html .= '</div>';

    $block = [
        'features' => [
            '#type' => 'markup',
            '#markup' => $html
        ]
    ];

    return $block;
}

function wz_main_articles_block_view()
{
    $main = new Main();
    $articles = $main->articles();
    $html = '<div class="inner">';
    $html .= '<ul class="lc01">';
    $i = 1;
    foreach($articles as $item) {
        $html .= '<li class="l'.$i++.'">
            <a href="/node/'.$item['nid'].'" class="thumb"><span><img src="'.$item['img'].'" alt="'.htmlspecialchars($item['title']).'"/></span></a>
            <dl class="conA">
                <dt>
                    <i>'.$item['category'].'</i>
                    <a href="/node/'.$item['nid'].'">'.$item['title'].'</a>
                </dt>
                <dd>'.$item['writer'].'</dd>
            </dl>
        </li>';
    }
    $html .= '</ul>';
    $html .= '<div class="clear"></div>';
    $html .= '</div>';
    return [
        'articles' => [
            '#type' => 'markup',
            '#markup' => $html
        ]
    ];
}

function wz_main_newsletter_block_view()
{

}

/**
 * Implements hook_theme_registry_alter().
 */
function wz_block_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'wz_block');
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  foreach ($template_file_objects as $key => $template_file_object) {
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
?>
